name: Helm Chart Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # Sometimes chart-releaser might fetch an outdated index.yaml from gh-pages, causing a WAW hazard on the repo
  # This job checks the remote file is up to date with the local one on release
  validate-gh-pages-index:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download remote index file and check equality
        run: |
          curl -vsSL https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml > index.yaml.remote
          LOCAL="$(md5sum < index.yaml)"
          REMOTE="$(md5sum < index.yaml.remote)"
          echo "$LOCAL" = "$REMOTE"
          test "$LOCAL" = "$REMOTE"

  chart-release:
    name: Create chart release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    needs: [ validate-gh-pages-index ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Add bitnami repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Release workload charts
        uses: ./.github/actions/chart_releaser
        with:
          config: .github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  gitops_update:
    runs-on: ubuntu-latest
    name: Update GitOps Repo
    needs:
      - chart-release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Add SSH key
        env:
          DITP_GITOPS_REPO_SECRET: ${{ secrets.DITP_GITOPS_REPO_SECRET }}
        run: |
          mkdir -p ~/.ssh
          echo "$DITP_GITOPS_REPO_SECRET" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Clone gitops-repo
        run: |
          git clone git@github.com:bcgov-c/ministry-gitops-ditp.git
          cd ministry-gitops-ditp
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Lookup latest chart
        id: chart_version
        run: |
          helm repo add traction https://bcgov.github.io/traction
          helm repo update
          echo "::set output name=APP_VERSION::$(helm search repo vc-authn-oidc --version ^0.3 -ojson | jq '.[0].app_version')"
          echo "::set output name=CHART_VERSION::$(helm search repo traction --version ^0.3 -ojson | jq '.[0].version')"
      - name: Update test
        env:
          APP_VERSION: ${{ steps.chart_version.outputs.APP_VERSION }}
          CHART_VERSION: ${{ steps.chart_version.outputs.CHART_VERSION }}
        run: |
          cd ministry-gitops-ditp
          yq e -i '.appVersion = $APP_VERSION' services/vc-authn-oidc/charts/test/Chart.yaml
          yq e -i '.version = $CHART_VERSION' services/traction/charts/test/Chart.yaml
      - name: Update prod
        env:
          APP_VERSION: ${{ steps.chart_version.outputs.APP_VERSION }}
          CHART_VERSION: ${{ steps.chart_version.outputs.CHART_VERSION }}
        run: |
          cd ministry-gitops-ditp
          yq e -i '.appVersion = $APP_VERSION' services/vc-authn-oidc/charts/prod/Chart.yaml
          yq e -i '.version = $CHART_VERSION' services/traction/charts/prod/Chart.yaml
      - name: Commit and push changes
        run: |
          cd ministry-gitops-ditp
          git add services/traction/charts/test/Chart.yaml services/traction/charts/prod/Chart.yaml
          git commit -m "Update chart version and image tags"
          git push origin main
